### ISSUE TITLE
About loss functions

### ISSUE THREAD

**Issue by sqlkrad** [airaria/TextBrewer#11]
Hi, thanks for your great work! I have a question about loss functions. Are there any experiments about which loss function is preferable between *kd_mse_loss* and *kd_ce_loss*?

**Comment by airaria** [comment]
I'm glad you like this work!

For classification tasks, _kd_ce_loss_ is preferable to  _kd_mse_loss_ in most cases. 
But limited by the computational resources, we couldn't perform a comprehensive benchmark. Thus the above conclusion is based on our preliminary experiment results. 
 
However, some authors are prefer to _kd_mse_loss_:
[Natural Language Generation for Effective Knowledge Distillation](https://www.aclweb.org/anthology/D19-6122/)
So we provide the both options.

If you are dealing with regression tasks, you should use _kd_mse_loss_ instead of _kd_ce_loss_, as stated in 
[_BAM! Born-Again Multi-Task Networks for Natural Language Understanding_](https://arxiv.org/abs/1907.04829)

**Comment by sqlkrad** [comment]
Thank you for you reply! I get it.
