### ISSUE TITLE
why use scheduler_class and scheduler_args rather than scheduler?

### ISSUE THREAD

**Issue by zhujiangang** [airaria/TextBrewer#12]
Can you please share with me the insights of deprecating "scheduler" and using "scheduler_class" and "scheduler_args" to construct the scheduler object? Thanks!

**Comment by airaria** [comment]
When initializing a lr scheduler, the optimizer needs to be provided, so that the scheduler knows what parameters are to be scheduled.
However, in some cases, for example when using intermediate losses, there are new parameters （params of dim matching layer) to be added to the optimizer inside the distiller. If the scheduler was initialized before we add new parameters to the optimizer, these newly added parameters won't be scheduled; therefore one solution to this problem is to construct the scheduler from scheduler_class and scheduler_args inside the distiller after updating the optimizer, instead of passing an existing one.

I hope my explanation will help!

**Comment by zhujiangang** [comment]
> When initializing an lr scheduler, the optimizer needs to be provided, so that the scheduler knows what parameters are to be scheduled.
> However, in some cases, for example when using intermediate losses, there are new parameters （params of dim matching layer) to be added to the optimizer inside the distiller. If the scheduler was initialized before we add new parameters to the optimizer, these newly added parameters won't be scheduled; therefore one solution to this problem is to construct the scheduler from scheduler_class and scheduler_args inside the distiller after updating the optimizer, instead of passing an existing one.
> 
> I hope my explanation will help!

Ah Yes! I'm clear now. Thank you!
