### ISSUE TITLE
How to customize teacher and student models, such as VGG in CV？

### ISSUE THREAD

**Issue by LiXuanming** [airaria/TextBrewer#44]
Hello, 
 authors

**Comment by airaria** [comment]
You can freely replace the teacher and the student with CV models.
But you can only use kd_loss for distillation. The inetermediate_matches are not available for those models, since the losses for the matchings are not designed for images.
(For example, for text, the matching loss receives tensor of shape (batch_size, length, hidden_dim),  which is not the shape of hidden states in CV)










在 2021-02-20 15:51:11，"LiXuanming" <notifications@github.com> 写道：

Hello,
authors
