### ISSUE TITLE
random_token_example error

### ISSUE THREAD

**Issue by tanyaroosta** [airaria/TextBrewer#81]
Hi,
I have pulled the latest repo and compiled the package.  When running the random_token_example/distill.py, I run into an issue as shown below.  I am not clear how to fix it, as it doesn't seem distill.py takes any user input, and so it should be running without any problems.

-------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-54d3a6b1009c> in <module>
     29 with distiller:
     30     distiller.train(optimizer, dataloader, num_epochs=num_epochs,
---> 31                     scheduler_class=scheduler_class, scheduler_args=scheduler_args, callback=callback_fun)

~/opt/anaconda3/lib/python3.7/site-packages/textbrewer/distiller_basic.py in train(self, optimizer, dataloader, num_epochs, scheduler_class, scheduler_args, scheduler, max_grad_norm, num_steps, callback, batch_postprocessor, **args)
    281             self.train_with_num_steps(optimizer, scheduler, tqdm_disable, dataloader, max_grad_norm, num_steps, callback, batch_postprocessor, **args)
    282         else:
--> 283             self.train_with_num_epochs(optimizer, scheduler, tqdm_disable, dataloader, max_grad_norm, num_epochs, callback, batch_postprocessor, **args)
    284 
    285 

~/opt/anaconda3/lib/python3.7/site-packages/textbrewer/distiller_basic.py in train_with_num_epochs(self, optimizer, scheduler, tqdm_disable, dataloader, max_grad_norm, num_epochs, callback, batch_postprocessor, **args)
    244                     if (global_step%train_steps_per_epoch in checkpoints) \
    245                             and ((current_epoch+1)%self.t_config.ckpt_epoch_frequency==0 or current_epoch+1==num_epochs):
--> 246                         self.save_and_callback(global_step, step, current_epoch, callback)
    247 
    248             logger.info(f"Epoch {current_epoch+1} finished")

~/opt/anaconda3/lib/python3.7/site-packages/textbrewer/distiller_general.py in save_and_callback(self, global_step, step, epoch, callback)
     63             self.model_T._forward_hooks = OrderedDict()
     64 
---> 65         super(GeneralDistiller, self).save_and_callback(global_step, step, epoch, callback)
     66 
     67         if self.has_custom_matches:

~/opt/anaconda3/lib/python3.7/site-packages/textbrewer/distiller_basic.py in save_and_callback(self, global_step, step, epoch, callback)
     36         if callback is not None:
     37             logger.info("Running callback function...")
---> 38             callback(model=self.model_S, step=global_step)
     39             self.model_S.train()
     40 

<ipython-input-1-ac3663f6f2de> in predict(model, eval_dataset, step, device)
     49         with torch.no_grad():
     50             logits, _ = model(input_ids=input_ids, attention_mask=attention_mask)
---> 51             cpu_logits = logits.detach().cpu()
     52         for i in range(len(cpu_logits)):
     53             pred_logits.append(cpu_logits[i].numpy())

AttributeError: 'str' object has no attribute 'detach'

**Comment by airaria** [comment]
Hi,
is your transformers version >= 4.0?
I think this problem is caused by the breaking change between transformers 4 and transformers 3.
In transformers 4, the output of the model is a dict-like object by default, rather than a tuple.


The solution is 
1. to call the model with the argument return_dict=False (line 50 in your program):
```python
 logits, _ = model(input_ids=input_ids, attention_mask=attention_mask, return_dict=False)
```
or 
2. unpatch the output correctly:
```python
 output = model(input_ids=input_ids, attention_mask=attention_mask)
logits = output[’logits’]
```
or
3. using transformers 3.




Hope it helps.
On 09/16/2021 ***@***.***> wrote：

Hi,
I have pulled the latest repo and compiled the package. When running the random_token_example/distill.py, I run into an issue as shown below. I am not clear how to fix it, as it doesn't seem distill.py takes any user input, and so it should be running without any problems.

AttributeError Traceback (most recent call last)
in
29 with distiller:
30 distiller.train(optimizer, dataloader, num_epochs=num_epochs,
---> 31 scheduler_class=scheduler_class, scheduler_args=scheduler_args, callback=callback_fun)

~/opt/anaconda3/lib/python3.7/site-packages/textbrewer/distiller_basic.py in train(self, optimizer, dataloader, num_epochs, scheduler_class, scheduler_args, scheduler, max_grad_norm, num_steps, callback, batch_postprocessor, **args)
281 self.train_with_num_steps(optimizer, scheduler, tqdm_disable, dataloader, max_grad_norm, num_steps, callback, batch_postprocessor, **args)
282 else:
--> 283 self.train_with_num_epochs(optimizer, scheduler, tqdm_disable, dataloader, max_grad_norm, num_epochs, callback, batch_postprocessor, **args)
284
285

~/opt/anaconda3/lib/python3.7/site-packages/textbrewer/distiller_basic.py in train_with_num_epochs(self, optimizer, scheduler, tqdm_disable, dataloader, max_grad_norm, num_epochs, callback, batch_postprocessor, **args)
244 if (global_step%train_steps_per_epoch in checkpoints)
245 and ((current_epoch+1)%self.t_config.ckpt_epoch_frequency==0 or current_epoch+1==num_epochs):
--> 246 self.save_and_callback(global_step, step, current_epoch, callback)
247
248 logger.info(f"Epoch {current_epoch+1} finished")

~/opt/anaconda3/lib/python3.7/site-packages/textbrewer/distiller_general.py in save_and_callback(self, global_step, step, epoch, callback)
63 self.model_T._forward_hooks = OrderedDict()
64
---> 65 super(GeneralDistiller, self).save_and_callback(global_step, step, epoch, callback)
66
67 if self.has_custom_matches:

~/opt/anaconda3/lib/python3.7/site-packages/textbrewer/distiller_basic.py in save_and_callback(self, global_step, step, epoch, callback)
36 if callback is not None:
37 logger.info("Running callback function...")
---> 38 callback(model=self.model_S, step=global_step)
39 self.model_S.train()
40

in predict(model, eval_dataset, step, device)
49 with torch.no_grad():
50 logits, _ = model(input_ids=input_ids, attention_mask=attention_mask)
---> 51 cpu_logits = logits.detach().cpu()
52 for i in range(len(cpu_logits)):
53 pred_logits.append(cpu_logits[i].numpy())

AttributeError: 'str' object has no attribute 'detach'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tanyaroosta** [comment]
Thanks for your reply and help.

Tanya

**Comment by tanyaroosta** [comment]
Hi Ziqing,
I have another question on the msra notebook. I was able to run it to the
point of training, however, when I started the training, I repeatedly saw
this error and the notebook finally froze:

[I 07:37:39.289 NotebookApp] Saving file at
/examples/notebook_examples/msra_ner.ipynb
[E 07:37:39.302 NotebookApp] Notebook JSON is invalid: {'version_major': 2,
'version_minor': 0, 'model_id': '2a114915871b4c7988a94fa7a633b646'} is not
valid under any of the given schemas

    Failed validating 'oneOf' in
display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:

    On
instance['cells'][7]['outputs'][0]['data']['application/vnd.jupyter.widget-view+json']:
    {'model_id': '2a114915871b4c7988a94fa7a633b646',
     'version_major': 2,
     'version_minor': 0}

Is there an issue on my end?

Thanks,

Tanya
