### ISSUE TITLE
Is there any methods can simplify the output during training?

### ISSUE THREAD

**Issue by HarryHe11** [airaria/TextBrewer#83]
Thx a lot for your work and contribution, this library is amazing！
But during KD, the output seems like:
```
  0% 0/1000 [00:00<?, ?it/s]11/02/2021 10:46:23 - INFO - Distillation -   Epoch 1
11/02/2021 10:46:23 - INFO - Distillation -   Length of current epoch in forward batch: 500

0it [00:00, ?it/s]
1it [00:00,  4.12it/s]
2it [00:00,  4.35it/s]
3it [00:00,  4.43it/s]
4it [00:00,  4.47it/s]
5it [00:01,  4.49it/s]
6it [00:01,  4.51it/s]
7it [00:01,  4.52it/s]
8it [00:01,  4.51it/s]
9it [00:02,  4.49it/s]
10it [00:02,  4.47it/s]
11it [00:02,  4.47it/s]
12it [00:02,  4.49it/s]
13it [00:02,  4.50it/s]
14it [00:03,  4.52it/s]
15it [00:03,  4.50it/s]
16it [00:03,  4.52it/s]
17it [00:03,  4.51it/s]
18it [00:04,  4.51it/s]
19it [00:04,  4.50it/s]
20it [00:04,  4.49it/s]
21it [00:04,  4.49it/s]
22it [00:04,  4.51it/s]
23it [00:05,  4.52it/s]
24it [00:05,  4.53it/s]11/02/2021 10:46:29 - INFO - Distillation -   Global step: 25, epoch step:25

25it [00:05,  4.53it/s]
26it [00:05,  4.52it/s]
27it [00:06,  4.50it/s]
28it [00:06,  4.49it/s]
29it [00:06,  4.49it/s]
30it [00:06,  4.49it/s]
31it [00:06,  4.48it/s]
32it [00:07,  4.47it/s]
33it [00:07,  4.44it/s]
34it [00:07,  4.46it/s]
35it [00:07,  4.47it/s]
36it [00:08,  4.47it/s]
37it [00:08,  4.48it/s]
38it [00:08,  4.47it/s]
39it [00:08,  4.47it/s]
40it [00:08,  4.49it/s]
41it [00:09,  4.51it/s]
42it [00:09,  4.52it/s]
43it [00:09,  4.52it/s]
44it [00:09,  4.53it/s]
45it [00:10,  4.53it/s]
46it [00:10,  4.53it/s]
47it [00:10,  4.53it/s]


```

It's kind of annoying, I just wanna see the evaluation result after each epoch, Is there any method that can get me rid of that?

**Comment by airaria** [comment]
You can set the distiller’s print_freq to a small value before start training. For example:
```
distiller.print_freq = 1
with distiller:
    ….
```
so that the distiller will print 1 log per epoch 


On 11/2/2021 ***@***.***> wrote：

Thx a lot for your work and contribution, this library is amazing！
But during KD, the output seems like:

  0% 0/1000 [00:00<?, ?it/s]11/02/2021 10:46:23 - INFO - Distillation -   Epoch 1

11/02/2021 10:46:23 - INFO - Distillation -   Length of current epoch in forward batch: 500



0it [00:00, ?it/s]

1it [00:00,  4.12it/s]

2it [00:00,  4.35it/s]

3it [00:00,  4.43it/s]

4it [00:00,  4.47it/s]

5it [00:01,  4.49it/s]

6it [00:01,  4.51it/s]

7it [00:01,  4.52it/s]

8it [00:01,  4.51it/s]

9it [00:02,  4.49it/s]

10it [00:02,  4.47it/s]

11it [00:02,  4.47it/s]

12it [00:02,  4.49it/s]

13it [00:02,  4.50it/s]

14it [00:03,  4.52it/s]

15it [00:03,  4.50it/s]

16it [00:03,  4.52it/s]

17it [00:03,  4.51it/s]

18it [00:04,  4.51it/s]

19it [00:04,  4.50it/s]

20it [00:04,  4.49it/s]

21it [00:04,  4.49it/s]

22it [00:04,  4.51it/s]

23it [00:05,  4.52it/s]

24it [00:05,  4.53it/s]11/02/2021 10:46:29 - INFO - Distillation -   Global step: 25, epoch step:25



25it [00:05,  4.53it/s]

26it [00:05,  4.52it/s]

27it [00:06,  4.50it/s]

28it [00:06,  4.49it/s]

29it [00:06,  4.49it/s]

30it [00:06,  4.49it/s]

31it [00:06,  4.48it/s]

32it [00:07,  4.47it/s]

33it [00:07,  4.44it/s]

34it [00:07,  4.46it/s]

35it [00:07,  4.47it/s]

36it [00:08,  4.47it/s]

37it [00:08,  4.48it/s]

38it [00:08,  4.47it/s]

39it [00:08,  4.47it/s]

40it [00:08,  4.49it/s]

41it [00:09,  4.51it/s]

42it [00:09,  4.52it/s]

43it [00:09,  4.52it/s]

44it [00:09,  4.53it/s]

45it [00:10,  4.53it/s]

46it [00:10,  4.53it/s]

47it [00:10,  4.53it/s]







It's kind of annoying, I just wanna see the evaluation result after each epoch, Is there any method that can get me rid of that?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HarryHe11** [comment]
Thanks!
