### ISSUE TITLE
是否能做预训练的蒸馏

### ISSUE THREAD

**Issue by YoungErm** [airaria/TextBrewer#87]
老师你好，我觉得这个蒸馏的工具包做的非常Nice。然后我有一个小问题，就是我能不能用它在预训练阶段做蒸馏。

**Comment by airaria** [comment]
可以，仿照序列标注任务的做法，只要替换相应loss即可


在2021年11月24日 ***@***.***> 写道：

老师你好，我觉得这个蒸馏的工具包做的非常Nice。然后我有一个小问题，就是我能不能用它在预训练阶段做蒸馏。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YoungErm** [comment]
好的谢谢老师
