### ISSUE TITLE
mnli main_train

### ISSUE THREAD

**Issue by Soulscb** [airaria/TextBrewer#88]
i want to train mnli_train.sh  and find load model error  "assert len(missing_keys) == 0"  i download the bert-base-chinese model

**Comment by airaria** [comment]
Would you give more information on the bash script you have run?
It looks like that the statement "assert len(missing_keys) == 0” is not in the examples/mnli_exmaple.
Do you mean the CMRC 2018 example?




On 12/6/2021 ***@***.***> wrote：

i want to train mnli_train.sh and find load model error "assert len(missing_keys) == 0" i download the bert-base-chinese model

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Soulscb** [comment]
我运行的是  run_mnli_train.sh ，并且报错发生在162行

**Comment by Soulscb** [comment]
File "main.trainer.py", line 161, in main
    assert len(missing_keys) == 0
AssertionError

**Comment by airaria** [comment]
你用最新的example试试？
你看下git目录里的examples/mnli_example，main.trainer.py的第161行并不是assert len(missing_keys) == 0，
你跑这个例子呢？
On 12/7/2021 ***@***.***> wrote：

File "main.trainer.py", line 161, in main
assert len(missing_keys) == 0
AssertionError

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Soulscb** [comment]
我发现了新的错误，我想知道你们实现的代码是跑通的？目前github里面，transformers=3.2.0 pytorch=1.2.0
